# Generated by Django 4.2.16 on 2024-11-17 17:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_tg_id', models.BigIntegerField(unique=True, verbose_name='Telegram ID пользователя')),
                ('first_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Имя')),
                ('last_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Фамилия')),
                ('username', models.CharField(blank=True, max_length=255, null=True, verbose_name='Telegram Username')),
                ('language_code', models.CharField(blank=True, max_length=10, null=True, verbose_name='Язык интерфейса')),
                ('is_bot', models.BooleanField(default=False, verbose_name='Это бот')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен в данный момент')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Удалено')),
            ],
            options={
                'verbose_name': 'Пользователь',
                'verbose_name_plural': 'Пользователи',
            },
        ),
        migrations.CreateModel(
            name='Record',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Имя пользователя')),
                ('age', models.PositiveIntegerField(blank=True, null=True, verbose_name='Возраст')),
                ('location', models.JSONField(blank=True, null=True, verbose_name='Локация')),
                ('is_military', models.BooleanField(blank=True, null=True, verbose_name='Состоит на военной службе')),
                ('educational_goal', models.CharField(blank=True, max_length=255, null=True, verbose_name='Образовательная цель')),
                ('telephone', models.CharField(blank=True, max_length=15, null=True, verbose_name='Телефон')),
                ('is_end', models.BooleanField(default=False, verbose_name='Завершено')),
                ('is_completed', models.BooleanField(default=False, verbose_name='Обучение завершено')),
                ('completion_comment', models.CharField(blank=True, max_length=500, null=True, verbose_name='Комментарий к обучению')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Удалено')),
                ('user_tg_id', models.OneToOneField(db_column='user_tg_id', on_delete=django.db.models.deletion.CASCADE, related_name='records', to='cbs.user', to_field='user_tg_id', verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Заявка',
                'verbose_name_plural': 'Заявки',
            },
        ),
    ]
