# Generated by Django 5.1.3 on 2024-11-26 20:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cbs', '0003_alter_district_name_city_unique_city_in_region_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='city',
            options={'verbose_name': 'Город', 'verbose_name_plural': 'Города'},
        ),
        migrations.AlterModelOptions(
            name='district',
            options={'verbose_name': 'Область', 'verbose_name_plural': 'Области'},
        ),
        migrations.AlterModelOptions(
            name='region',
            options={'verbose_name': 'Регион', 'verbose_name_plural': 'Регионы'},
        ),
    ]
