version: "3.8"

services:

  django:
    env_file:
      - .env
    build:
      context: .
      dockerfile: Dockerfile
      args:
        HOST: ${HOST}
        DJANGO_PORT: ${DJANGO_PORT}
    container_name: django_container
    env_file:
      - .env
    environment:
      - ALLOWED_HOSTS=${HOST},0.0.0.0
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    volumes:
      - ./django:/django
      - static:/django/static
      - media:/django/media
    ports:
      - "${DJANGO_PORT}:8000"
    depends_on:
      - postgres
    networks:
      - app_network

  postgres:
    build:
      context: .
      dockerfile: DockerPostgresql
    privileged: true
    container_name: postgres_container
    env_file:
      - .env
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "${POSTGRES_PORT}:5432"
    volumes:
      - ./data:/var/lib/postgresql/data
    networks:
      - app_network

  nginx:
    build:
      context: ./nginx
      dockerfile: DockerfileNginx
    container_name: nginx_container
    env_file:
      - .env
    environment:
      - HOST=${HOST}
    ports:
      - "${NGINX_PORT}:80"
    depends_on:
      - django
    volumes:
      - ./nginx/conf:/etc/nginx/templates
      - static:/django/static
      - media:/django/media
    networks:
      - app_network


networks:
  app_network:
    driver: overlay     
    driver_opts:       
      com.docker.network.driver.mtu: 1450

volumes:
  static:
  media: